version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/tetris
    ports:
      - 3000:3000
    image: tetris:react
    container_name: tetris-reactjs
    command: npm start