
version: 2.1
jobs:
    build:
        docker:
            - image: cimg/node:18.8.0
        # Setting env ci = false will ignore warnings 
        working_directory: ~/repo
        environment:
          CI: false
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package-lock.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: npm install

            - save_cache:
                  paths:
                      - ./node_modules
                  key: v1-dependencies-{{ checksum "package-lock.json" }}
            - run:
                  name: Build
                  command: npm run build
            - run:
                  name: Firebase Deploy
                  command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting